name: DockerTar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Construir la imagen Docker
      run: |
        docker build -t lujuria .

    - name: Guardar la imagen como tar.gz
      run: |
        docker save -o lujuria.tar lujuria

    - name: Subir la imagen como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: lujuria
        path: lujuria.tar
